/**
 * This file is the entry point for the browser and is responsible for hydrating
 * the markup generated by the server in your server entry module.
 *
 * See https://remix.run/file-conventions/entry.client
 */

import { RemixBrowser } from "@remix-run/react"
import { StrictMode, startTransition } from "react"
import { hydrateRoot } from "react-dom/client"

startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
      <RemixBrowser />
    </StrictMode>,
  )
})
