/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/root/index.ts'
import { Route as RoutesHelpIndexImport } from './routes/help/index.ts'
import { Route as RoutesFoodsIndexImport } from './routes/foods/index.ts'
import { Route as RoutesIndexIndexImport } from './routes/index/index.ts'

// Create/Update Routes

const RoutesHelpIndexRoute = RoutesHelpIndexImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRoute,
} as any)

const RoutesFoodsIndexRoute = RoutesFoodsIndexImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRoute,
} as any)

const RoutesIndexIndexRoute = RoutesIndexIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RoutesIndexIndexImport
      parentRoute: typeof rootRoute
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof RoutesFoodsIndexImport
      parentRoute: typeof rootRoute
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof RoutesHelpIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof RoutesIndexIndexRoute
  '/foods': typeof RoutesFoodsIndexRoute
  '/help': typeof RoutesHelpIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof RoutesIndexIndexRoute
  '/foods': typeof RoutesFoodsIndexRoute
  '/help': typeof RoutesHelpIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof RoutesIndexIndexRoute
  '/foods': typeof RoutesFoodsIndexRoute
  '/help': typeof RoutesHelpIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/foods' | '/help'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/foods' | '/help'
  id: '__root__' | '/' | '/foods' | '/help'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RoutesIndexIndexRoute: typeof RoutesIndexIndexRoute
  RoutesFoodsIndexRoute: typeof RoutesFoodsIndexRoute
  RoutesHelpIndexRoute: typeof RoutesHelpIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  RoutesIndexIndexRoute: RoutesIndexIndexRoute,
  RoutesFoodsIndexRoute: RoutesFoodsIndexRoute,
  RoutesHelpIndexRoute: RoutesHelpIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "./routes/root/index.ts",
      "children": [
        "/",
        "/foods",
        "/help"
      ]
    },
    "/": {
      "filePath": "./routes/index/index.ts"
    },
    "/foods": {
      "filePath": "./routes/foods/index.ts"
    },
    "/help": {
      "filePath": "./routes/help/index.ts"
    }
  }
}
ROUTE_MANIFEST_END */
