import _ from "lodash/fp.js"

const foods = [
  {
    id: "244461393",
    name: "Rolled Oats",
    brand: "",
    carbs: 70,
    proteins: 13,
    fats: 6,
  },
  {
    id: "244461394",
    name: "Chia Seeds",
    brand: "",
    carbs: 40,
    proteins: 18,
    fats: 30,
  },
  {
    id: "244461395",
    name: "Flax Seeds",
    brand: "",
    carbs: 29,
    proteins: 18,
    fats: 42,
  },
  {
    id: "244461396",
    name: "Pumpkin Seeds",
    brand: "",
    carbs: 11,
    proteins: 30,
    fats: 49,
  },
  {
    id: "244461397",
    name: "White Rice",
    brand: "",
    carbs: 79,
    proteins: 7,
    fats: 1,
  },
  {
    id: "244461398",
    name: "Brown Rice",
    brand: "",
    carbs: 76,
    proteins: 8,
    fats: 3,
  },
  {
    id: "244461399",
    name: "Amaranth",
    brand: "",
    carbs: 65,
    proteins: 14,
    fats: 7,
  },
  {
    id: "244461312",
    name: "Quinoa",
    brand: "",
    carbs: 64,
    proteins: 14,
    fats: 6,
  },
  {
    id: "244461313",
    name: "Potato",
    brand: "",
    carbs: 17,
    proteins: 2,
    fats: 0,
  },
  {
    id: "244461314",
    name: "Whole Wheat Pita",
    brand: "",
    carbs: 56,
    proteins: 10,
    fats: 2,
  },
  {
    id: "244461315",
    name: "Nutritional Yeast",
    brand: "",
    carbs: 31,
    proteins: 50,
    fats: 3,
  },
  {
    id: "244461316",
    name: "Spirulina",
    brand: "",
    carbs: 24,
    proteins: 58,
    fats: 8,
  },
  {
    id: "244461317",
    name: "Pumpkin",
    brand: "",
    carbs: 7,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461318",
    name: "Taro (Malanga)",
    brand: "",
    carbs: 26,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461319",
    name: "Yam (Ñame)",
    brand: "",
    carbs: 28,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461320",
    name: "Sweet Potato",
    brand: "",
    carbs: 20,
    proteins: 2,
    fats: 0,
  },
  {
    id: "244461321",
    name: "Red Onion",
    brand: "",
    carbs: 10,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461322",
    name: "White Onion",
    brand: "",
    carbs: 8,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461323",
    name: "Yellow Onion",
    brand: "",
    carbs: 9,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461324",
    name: "Broccoli",
    brand: "",
    carbs: 6,
    proteins: 3,
    fats: 0,
  },
  {
    id: "244461325",
    name: "Carrots",
    brand: "",
    carbs: 10,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461326",
    name: "Pistachios",
    brand: "",
    carbs: 27,
    proteins: 20,
    fats: 45,
  },
  {
    id: "244461327",
    name: "Walnuts",
    brand: "",
    carbs: 14,
    proteins: 15,
    fats: 65,
  },
  {
    id: "244461328",
    name: "Cashews",
    brand: "",
    carbs: 30,
    proteins: 18,
    fats: 44,
  },
  {
    id: "244461329",
    name: "Almonds",
    brand: "",
    carbs: 22,
    proteins: 21,
    fats: 50,
  },
  {
    id: "244461330",
    name: "Pecans",
    brand: "",
    carbs: 14,
    proteins: 9,
    fats: 72,
  },
  {
    id: "244461331",
    name: "Lentils",
    brand: "",
    carbs: 63,
    proteins: 25,
    fats: 1,
  },
  {
    id: "244461332",
    name: "Black Beans",
    brand: "",
    carbs: 62,
    proteins: 22,
    fats: 1,
  },
  {
    id: "244461333",
    name: "Kidney Beans",
    brand: "",
    carbs: 61,
    proteins: 23,
    fats: 1,
  },
  {
    id: "244461334",
    name: "Chickpeas",
    brand: "",
    carbs: 63,
    proteins: 20,
    fats: 6,
  },
  {
    id: "244461335",
    name: "Shiitake Mushrooms",
    brand: "",
    carbs: 7,
    proteins: 2,
    fats: 0,
  },
  {
    id: "244461336",
    name: "Portabella Mushrooms",
    brand: "",
    carbs: 4,
    proteins: 2,
    fats: 0,
  },
  {
    id: "244461337",
    name: "Prunes",
    brand: "",
    carbs: 64,
    proteins: 2,
    fats: 0,
  },
  {
    id: "244461338",
    name: "Banana",
    brand: "",
    carbs: 23,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461339",
    name: "Strawberries",
    brand: "",
    carbs: 8,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461340",
    name: "Roasted Almond Butter",
    brand: "Whole Foods",
    carbs: 28,
    proteins: 14,
    fats: 39,
  },
  {
    id: "244461341",
    name: "Pea Milk",
    brand: "Ripple",
    carbs: 2,
    proteins: 3,
    fats: 2,
  },
  {
    id: "244461342",
    name: "2% Fat Cottage Cheese",
    brand: "365",
    carbs: 4,
    proteins: 11,
    fats: 2,
  },
  {
    id: "244461343",
    name: "1% Fat Yogurt",
    brand: "Green Valley",
    carbs: 5,
    proteins: 5,
    fats: 1,
  },
  {
    id: "244461344",
    name: "Butter",
    brand: "",
    carbs: 0,
    proteins: 1,
    fats: 81,
  },
  {
    id: "244461345",
    name: "Egg",
    brand: "",
    carbs: 1,
    proteins: 13,
    fats: 11,
  },
  {
    id: "244461346",
    name: "Apple",
    brand: "",
    carbs: 15,
    proteins: 0,
    fats: 0,
  },
  {
    id: "244461347",
    name: "Chickpea Flour",
    brand: "Bob's Red Mill",
    carbs: 70,
    proteins: 17,
    fats: 5,
  },
  {
    id: "244461348",
    name: "Maple Syrup",
    brand: "365",
    carbs: 67,
    proteins: 0,
    fats: 0,
  },
  {
    id: "244461349",
    name: "Oil",
    brand: "",
    carbs: 0,
    proteins: 0,
    fats: 94,
  },
  {
    id: "244461350",
    name: "Polenta",
    brand: "Bob's Red Mill",
    carbs: 77,
    proteins: 9,
    fats: 0,
  },
  {
    id: "244461351",
    name: "Hulled Hemp Seeds",
    brand: "",
    carbs: 9,
    proteins: 32,
    fats: 49,
  },
  {
    id: "244461352",
    name: "Millet",
    brand: "",
    carbs: 73,
    proteins: 11,
    fats: 4,
  },
  {
    id: "244461353",
    name: "Medjool Date",
    brand: "",
    carbs: 75,
    proteins: 2,
    fats: 0,
  },
  {
    id: "244461354",
    name: "Tomato",
    brand: "",
    carbs: 4,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461355",
    name: "Avocado",
    brand: "",
    carbs: 9,
    proteins: 2,
    fats: 15,
  },
  {
    id: "244461356",
    name: "Firm Tofu",
    brand: "",
    carbs: 3,
    proteins: 17,
    fats: 9,
  },
  {
    id: "244461357",
    name: "Wild Rice",
    brand: "",
    carbs: 75,
    proteins: 15,
    fats: 1,
  },
  {
    id: "244461358",
    name: "Asparagus",
    brand: "",
    carbs: 4,
    proteins: 2,
    fats: 0,
  },
  {
    id: "244461359",
    name: "Tempeh",
    brand: "Lightlife",
    carbs: 13,
    proteins: 23,
    fats: 10,
  },
  {
    id: "244461360",
    name: "Steel Cut Oats",
    brand: "Bob's Red Mill",
    carbs: 70,
    proteins: 11,
    fats: 6,
  },
  {
    id: "244461361",
    name: "Shallots",
    brand: "",
    carbs: 17,
    proteins: 3,
    fats: 0,
  },
  {
    id: "244461362",
    name: "Arugula",
    brand: "",
    carbs: 4,
    proteins: 3,
    fats: 1,
  },
  {
    id: "244461363",
    name: "Red Bell Pepper",
    brand: "",
    carbs: 6,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461364",
    name: "Green Bell Pepper",
    brand: "",
    carbs: 5,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461365",
    name: "Zucchini",
    brand: "",
    carbs: 3,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461366",
    name: "Edamame",
    brand: "",
    carbs: 9,
    proteins: 12,
    fats: 5,
  },
  {
    id: "244461367",
    name: "Winter Squash",
    brand: "",
    carbs: 9,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461368",
    name: "Raisins",
    brand: "",
    carbs: 79,
    proteins: 3,
    fats: 0,
  },
  {
    id: "244461369",
    name: "Beets",
    brand: "",
    carbs: 10,
    proteins: 2,
    fats: 0,
  },
  {
    id: "244461370",
    name: "Parsnips",
    brand: "",
    carbs: 18,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461371",
    name: "Blueberries",
    brand: "",
    carbs: 15,
    proteins: 1,
    fats: 0,
  },
  {
    id: "244461372",
    name: "Plant Protein",
    brand: "Orgain",
    carbs: 33,
    proteins: 46,
    fats: 9,
  },
  {
    id: "244461373",
    name: "4% Fat Cottage Cheese",
    brand: "365",
    carbs: 4,
    proteins: 11,
    fats: 4,
  },
  {
    id: "244461374",
    name: "Plain Organic Yogurt",
    brand: "Seven Stars Farm",
    carbs: 4,
    proteins: 3,
    fats: 4,
  },
]

const makeFoods = (size = 5) =>
  _.sampleSize(size, foods).map(({ id }) => ({
    id,
    amount: _.random(50, 150),
  }))

const steps = [
  "Preheat oven to 425°F.",
  "Cut off the woody bottom part of the asparagus spears and discard.",
  'With a vegetable peeler, peel off the skin on the bottom 2-3 inches of the spears (this keeps the asparagus from being all.",string.", and if you eat asparagus you know what I mean by that).',
  "Place asparagus on foil-lined baking sheet and drizzle with olive oil.",
  "Sprinkle with salt.",
  "With your hands, roll the asparagus around until they are evenly coated with oil and salt.",
  "Roast for 10-15 minutes, depending on the thickness of your stalks and how tender you like them.",
  "They should be tender when pierced with the tip of a knife.",
  "The tips of the spears will get very brown but watch them to prevent burning.",
  "They are great plain, but sometimes I serve them with a light vinaigrette if we need something acidic to balance out our meal.",
]

const recipes = [
  { id: "245461393", name: "Chili", steps, ingredients: makeFoods() },
  { id: "245461394", name: "Pasta", steps, ingredients: makeFoods() },
  { id: "245461395", name: "Bean Soup", steps, ingredients: makeFoods() },
  { id: "245461396", name: "Steamed Rice", steps, ingredients: makeFoods() },
  { id: "245461397", name: "Apple Pie", steps, ingredients: makeFoods() },
  { id: "245461398", name: "Muffins", steps, ingredients: makeFoods() },
]

const recipesIds = _.map("id", recipes)

const meals = [
  { name: "Breakfast", foods: makeFoods(), recipes: recipesIds },
  { name: "Morning Snack", foods: makeFoods(), recipes: recipesIds },
  { name: "Lunch", foods: makeFoods(), recipes: recipesIds },
  { name: "Afternoon Snack", foods: makeFoods(), recipes: recipesIds },
  { name: "Dinner", foods: makeFoods(), recipes: recipesIds },
  { name: "Evening Snack", foods: makeFoods(), recipes: recipesIds },
]

export const data = {
  tab: 0,
  target: { carbs: 0, proteins: 0, fats: 0 },
  foods,
  recipes,
  meals,
}
