/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/root/index.ts'
import { Route as RoutesIndexIndexImport } from './routes/index/index.ts'

// Create/Update Routes

const RoutesIndexIndexRoute = RoutesIndexIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RoutesIndexIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof RoutesIndexIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof RoutesIndexIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof RoutesIndexIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RoutesIndexIndexRoute: typeof RoutesIndexIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  RoutesIndexIndexRoute: RoutesIndexIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "./routes/root/index.ts",
      "children": [
        "/"
      ]
    },
    "/": {
      "filePath": "./routes/index/index.ts"
    }
  }
}
ROUTE_MANIFEST_END */
